name: Feature Request
description: Suggest a new feature or enhancement for the Merit Badge Manager
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe the feature or enhancement you would like to see.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: The application needs a secure configuration management system that handles API keys, database connections, file paths, and other configurable settings without hardcoding values or committing sensitive information to the repository. All configuration should be externalized and environment-specific.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this solved?
      placeholder: Implement a configuration management system using environment variables, configuration files, and secure secret storage. Include support for different environments (development, testing, production), validation of configuration values, and clear documentation for setup and deployment. Ensure no sensitive information is ever committed to the repository.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: |
        Key requirements:
        - Environment variable support for all configurable values
        - Secure configuration files excluded from version control
        - Configuration validation and error handling
        - Support for multiple environments
        - Database connection string management
        - File path and directory configuration
        - API key and credential management
        - Clear setup documentation
        - Follow security requirements - no hardcoded secrets
