name: Feature Request
description: Suggest a new feature or enhancement for the Merit Badge Manager
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Please describe the feature or enhancement you would like to see.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: Describe the problem or pain point.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this solved?
      placeholder: Describe your ideal solution or feature.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
      placeholder: Optional
